server:
  port: 8080

spring:
  datasource:
    username: root
    password: wyh19950212
    url: jdbc:mysql://localhost:3306/learningdb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  ##redis
  redis:
    database: 4
    host: 39.108.251.115
    namespace: base:session
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    password: wyh19950212
    port: 6379

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ehi.*.model

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

#日期类型格式
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#日期类型使用中国时区
spring:
  jackson:
    time-zone: GMT+8
#序列化所有参数
spring:
  jackson:
    default-property-inclusion: always

upload:
  chunkSize: 2 #单位为M
  thread:
    maxSize: 25
  queue:
    maxSize: 100
  root:
    dir: /file/uploads
  window: #window系统指定盘符
    root: D:/