#日期类型格式
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#日期类型使用中国时区
spring:
  jackson:
    time-zone: GMT+8
#序列化所有参数
spring:
  jackson:
    default-property-inclusion: always

upload:
  chunkSize: 2 #单位为M
  thread:
    maxSize: 25
  queue:
    maxSize: 100
  root:
    dir: /file/uploads
  window: #window系统指定盘符
    root: D:/